### PR TITLE
Fix MaxMind database fetching

### LINKED ISSUE #162: MaxMind database fetching is broken due to privacy change on MaxMind side
https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

Requires a license key now.

### PR DESCRIPTION
**Pull request by dwightwatson**
This is a follow-up to #163 that is intended to fix #162.

It expands on the work by @tylermann - with a couple of differences.

Instead of adding the database filename to the config it searches for the first file with the extension `.mmdb` and assumes this is the correct one. Seems like a little simpler to me though less configurable - open to feedback here.

It would be great if we could leverage Laravel's filesystem adapter as it would clean up much of the directory creation/removal code, but that's probably part of a larger discussion.

### CODE REVIEW

**Comment by dwightwatson** [comment]
This is likely to still fail because there is no licence key on the testing server - so it's a matter of getting a licence key for testing, stubbing out the download or removing the test completely.

File: src/Services/MaxMindDatabase.php [hunk 1]
```diff
@@ -66,27 +67,98 @@ public function update()
...
+            if ($file->isDir()) {
+                return $this->findDatabaseFile(new PharData($file->getPathName()));
+            }
 
-        // Unzip and save database
-        file_put_contents($path, gzopen($tmpFile, 'r'));
+            if (pathinfo($file, PATHINFO_EXTENSION) === 'mmdb') {
+                return $file;
+            }
+        }
```
Comment (tylermann) [inline src/Services/MaxMindDatabase.php]: Could potentially explicitly `return null` at the end here instead of an implicit void in case the file wasn't matched but up to you. I just usually like having a function either always return something or always not return something for readability, but that may also just be me so feel free to ignore.

Comment (dwightwatson) [reply src/Services/MaxMindDatabase.php]: Not opposed to it, it's nice that it's more explicit. I've made the change.

Comment (dwightwatson) [reply src/Services/MaxMindDatabase.php]: Better yet - I've moved the exception into the method. Means I don't have to do the `is_null` check further up.

**Comment by theblindfrog** [comment]
@Torann are you able to review this PR?

**Comment by Torann** [comment]
Going over it today

**Comment by Torann** [comment]
This looks great!!! I'm thinking since people have to update their config file, which is out of our hands, I'm going to mark this a version 1.1 which will then require people to go over the upgrade doc. @dwightwatson if you wouldn't mind could you update [upgrade.md](https://github.com/Torann/lyften.com/blob/master/source/projects/laravel-geoip/_doc/upgrade.md) on Lyften.com with the best way for people to go about upgrading from v1.0 to v1.1

How does this sound?

**Comment by dwightwatson** [comment]
Makes sense, no worries - just made a quick PR that goes over the change: https://github.com/Torann/lyften.com/pull/17

**Comment by Torann** [comment]
Ok, making the release version now and the docs are being deployed now. Thanks!
